name: "auto-readme"
on:
  workflow_dispatch: {}

  ## Added pull_request to register workflow from the PR.
  ## Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
  pull_request:
    branches-ignore: ['*']

  schedule:
    # Example of job definition:
    # .---------------- minute (0 - 59)
    # |  .------------- hour (0 - 23)
    # |  |  .---------- day of month (1 - 31)
    # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
    # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
    # |  |  |  |  |
    # *  *  *  *  * user-name command to be executed

    # Update README.md nightly at 4am UTC
    - cron:  '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          banner_enabled: true
          readme_enabled: true
          github_access_token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}